spring:
  datasource:
    url: ${H2_URL:jdbc:h2:mem:shopDb}
    username: ${H2_USER:user}
    password: ${H2_PASSWORD:user}

  liquibase:
    url: ${H2_URL:jdbc:h2:mem:shopDb}
    user: ${H2_USER:user}
    password: ${H2_PASSWORD:user}
    change-log: classpath:/db/changelog/init.xml
    enabled: true
